  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: client1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
server:
  port: 8081

#mybatis插件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ljq.client1.entity

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
env: test
